name: train and test using docker image
on :
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'data/**'
      - 'requirements.txt'
      - 'README.md'
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: alcinasharon21/mlops:latest

      - name: Pull Docker image
        run: docker pull alcinasharon21/mlops:latest

      - name: Run Docker container
        run: docker run --rm alcinasharon21/mlops:latest

      - name: Execute Docker image
        # id: extract-score
        # run: echo "::set-output name=score::$(docker run --rm alcinasharon21/mlops:latest | grep 'Score:' | awk '{print $2}')"
        run:
          OUTPUT=$(docker run --rm alcinasharon21/mlops:latest)
          echo "Score:"
          echo "$OUTPUT"
          if [[ `echo "$OUTPUT 0.30" | awk '{print ($1 < $2)}'` == 1 ]]; then echo "Insufficient Accuracy" && exit 1; fi