name: train and test using docker image
on :
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'data/**'
      - 'requirements.txt'
      - 'README.md'
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: alcinasharon21/mlops:latest

      - name: Pull Docker image
        run: docker pull alcinasharon21/mlops:latest

      - name: Run Docker container
        run: docker run --rm alcinasharon21/mlops:latest

      - name: Execute Docker image
        # id: extract-score
        # run: echo "::set-output name=score::$(docker run --rm alcinasharon21/mlops:latest | grep 'Score:' | awk '{print $2}')"
        run:
          OUTPUT=$(docker run --rm alcinasharon21/mlops:latest)
          echo "::set-output name=output::$output"
      - name: Check output value
        run: |
            output=${{ steps.execute_docker_image.outputs.output }}
            if [ $(echo "$output < 0.30" | bc -l) -eq 1 ]; then
              echo "Output value is less than 0.30"
            else
              echo "Output value is greater than or equal to 0.30"
              exit 1
            fi