name: train and test using docker image

on: push
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: alcinasharon21/mlops:latest

      - name: Pull Docker image
        run: docker pull alcinasharon21/mlops:latest

      - name: Run Docker container
        run: docker run --rm alcinasharon21/mlops:latest